version: "3"
services:
  bank-jdbc:
    image: bank-jdbc
    ports:
      - "8080:8080"
    networks:
      - bank-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - bank-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bank

networks:
  bank-mysql: